import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowLeft, ArrowRight, Check, ChevronDown, Clapperboard, FileText, Film, FolderOpen, Layers3,
  LoaderCircle, Menu, MoreHorizontal, Play, Plus, RotateCcw, ScanSearch, Settings2, Sparkles,
  Search, ListFilter, Trash2, Upload, UsersRound, WandSparkles, X,
} from "lucide-react";
import { api } from "./api";
import type { DashboardData, Episode, LlmSettings, PipelineData, Project, Shot, Subject } from "./types";

type Stage = "setup" | "format" | "episodes" | "subjects" | "shots" | "render";
type WorkingAction = "setup" | "generate" | "format" | "episodes" | "subjects" | "shots" | "render" | "delete";
const stages: Array<{ id: Stage; label: string; description: string; icon: typeof FileText }> = [
  { id: "setup", label: "项目设定", description: "确定项目规格", icon: Settings2 },
  { id: "format", label: "剧本格式化", description: "整理标准剧本", icon: WandSparkles },
  { id: "episodes", label: "剧本解析", description: "分集与情节结构", icon: Layers3 },
  { id: "subjects", label: "主体生成", description: "角色 · 场景 · 道具", icon: UsersRound },
  { id: "shots", label: "故事板", description: "生成分镜内容", icon: ScanSearch },
  { id: "render", label: "生成视频", description: "进入渲染队列", icon: Clapperboard },
];
const sampleScript = `午夜车站
类型：悬疑短片

场次一：外景，旧车站，夜
雨停了。林默站在空荡的月台，检查最后一盏信号灯。

林默：今晚不会再有人来了。

场次二：内景，检票亭，夜
一封没有寄件人的信从售票窗口滑进来，落款日期是二十年以后。

林默打开信，车站深处传来列车启动的声音。`;
const MAX_SCRIPT_LENGTH = 200000;
const emptyPipeline = (): PipelineData => ({ project: {} as Project, document: null, episodes: [], subjects: [], shots: [] });
const formatDuration = (seconds: number) => `${Math.floor(seconds / 60) ? `${Math.floor(seconds / 60)}m ` : ""}${String(seconds % 60).padStart(2, "0")}s`;
const getProjectTitle = (text: string) => text.split("\n").map((line) => line.trim()).find(Boolean)?.slice(0, 40) || "未命名剧本";

function App() {
  const [dashboard, setDashboard] = useState<DashboardData | null>(null);
  const [project, setProject] = useState<Project | null>(null);
  const [homeVisible, setHomeVisible] = useState(true);
  const [pipeline, setPipeline] = useState<PipelineData>(emptyPipeline());
  const [stage, setStage] = useState<Stage>("setup");
  const [setupDraft, setSetupDraft] = useState({ title: "", logline: "", genre: "悬疑", style: "电影写实", aspectRatio: "16:9", durationSeconds: 60, targetEpisodeCount: 3 });
  const [scriptText, setScriptText] = useState("");
  const [loading, setLoading] = useState(true);
  const [workingAction, setWorkingAction] = useState<WorkingAction | null>(null);
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const [toast, setToast] = useState("");
  const [error, setError] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [settings, setSettings] = useState<LlmSettings | null>(null);
  const [settingsBusy, setSettingsBusy] = useState(false);
  const [apiKeyDraft, setApiKeyDraft] = useState("");
  const [newProjectDialogOpen, setNewProjectDialogOpen] = useState(false);
  const [deleteTarget, setDeleteTarget] = useState<Project | null>(null);
  const [projectManagerVisible, setProjectManagerVisible] = useState(false);
  const [managerProjects, setManagerProjects] = useState<Project[]>([]);
  const [managerLoading, setManagerLoading] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);

  const loadProject = async (nextProject: Project, requestedStage?: Stage) => {
    setProject(nextProject);
    setHomeVisible(false);
    window.scrollTo(0, 0);
    setSetupDraft({ title: nextProject.title, logline: nextProject.logline, genre: nextProject.genre, style: nextProject.style, aspectRatio: nextProject.aspectRatio, durationSeconds: nextProject.durationSeconds, targetEpisodeCount: nextProject.targetEpisodeCount });
    try {
      const data = await api.pipeline(nextProject.id);
      setPipeline(data); setScriptText(data.document?.originalText ?? "");
      if (requestedStage) setStage(requestedStage);
      else if (data.shots.length) setStage("shots"); else if (data.subjects.length) setStage("subjects"); else if (data.episodes.length) setStage("episodes"); else if (data.document) setStage("format"); else setStage("setup");
    } catch (caught) { setToast(caught instanceof Error ? caught.message : "项目读取失败"); }
  };
  const refresh = async () => {
    try { const data = await api.dashboard(); setDashboard(data); }
    catch (caught) { setError(caught instanceof Error ? caught.message : "无法连接后端服务"); } finally { setLoading(false); }
  };
  const refreshProjectManager = async () => {
    setManagerLoading(true);
    try { setManagerProjects(await api.projects()); }
    catch (caught) { setToast(caught instanceof Error ? caught.message : "项目列表读取失败"); }
    finally { setManagerLoading(false); }
  };
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 3400); return () => window.clearTimeout(timer); }, [toast]);
  const currentIndex = stages.findIndex((item) => item.id === stage);
  const completion = useMemo(() => Math.round(([pipeline.document?.formatStatus === "formatted", pipeline.episodes.length > 0, pipeline.subjects.length > 0, pipeline.shots.length > 0].filter(Boolean).length / 4) * 100), [pipeline]);
  const working = workingAction !== null;
  const run = async <T,>(actionName: WorkingAction, action: () => Promise<T>, success: string | ((result: T) => string)) => { if (working) return; setWorkingAction(actionName); try { const result = await action(); setToast(typeof success === "function" ? success(result) : success); } catch (caught) { setToast(caught instanceof Error ? caught.message : "处理失败"); } finally { setWorkingAction(null); } };
  const projectInput = (draft: ProjectDraft) => ({ title: draft.title.trim(), logline: (draft.logline.trim() || `围绕${draft.title.trim()}展开的${draft.genre}故事。`).slice(0, 5000), genre: draft.genre, style: draft.style, aspectRatio: draft.aspectRatio, durationSeconds: Math.min(720, Math.max(15, draft.durationSeconds)), targetEpisodeCount: Math.min(100, Math.max(1, draft.targetEpisodeCount)) });
  const ensureProject = async () => { if (project) return project; const created = await api.createProject(projectInput({ ...setupDraft, title: setupDraft.title.trim() || getProjectTitle(scriptText) })); setProject(created); return created; };
  const saveProjectSetup = () => run("setup", async () => { const next = project ? await api.updateProject(project.id, projectInput(setupDraft)) : await ensureProject(); setProject(next); setHomeVisible(false); setDashboard(await api.dashboard()); setStage("format"); }, "项目设定已保存，请导入剧本");
  const generateProjectScript = () => run("generate", async () => { const input = projectInput(setupDraft); const next = project ? await api.updateProject(project.id, input) : await api.createProject(input); const result = await api.generateScript(next.id, input); const data = await api.pipeline(next.id); setProject(result.project); setScriptText(result.scriptText); setPipeline(data); setHomeVisible(false); setDashboard(await api.dashboard()); setStage("format"); }, "剧本草案已生成并保存，请开始格式化");
  const formatScript = () => run("format", async () => { const next = await ensureProject(); const result = await api.format(next.id, scriptText); setProject(result.project); setPipeline(await api.pipeline(next.id)); setStage("format"); }, "剧本已整理为标准格式");
  const extractEpisodes = () => run("episodes", async () => { const result = await api.extractEpisodes(project!.id); setProject(result.project); setPipeline((current) => ({ ...current, episodes: result.episodes })); setStage("episodes"); return result.episodes.length; }, (count) => `已拆分 ${count} 集剧情`);
  const extractSubjects = () => run("subjects", async () => { const result = await api.extractSubjects(project!.id); setProject(result.project); setPipeline((current) => ({ ...current, subjects: result.subjects })); setStage("subjects"); }, "已提取角色、场景与道具");
  const extractShots = () => run("shots", async () => { const result = await api.extractShots(project!.id); setProject(result.project); setPipeline((current) => ({ ...current, shots: result.shots })); setStage("shots"); return result.shots.length; }, (count) => `已生成 ${count} 个镜头`);
  const renderVideo = () => run("render", async () => { await api.render(project!.id); const data = await api.pipeline(project!.id); setPipeline(data); setProject(data.project); setStage("render"); await refresh(); }, "视频已加入渲染队列");
  const deleteProject = (item: Project) => setDeleteTarget(item);
  const confirmDeleteProject = () => {
    if (!deleteTarget) return;
    const item = deleteTarget;
    setDeleteTarget(null);
    void run("delete", async () => { await api.deleteProject(item.id); if (project?.id === item.id) goHome(); await refresh(); if (projectManagerVisible) await refreshProjectManager(); }, "项目已删除");
  };
  const openSettings = () => { setSettingsOpen(true); setSettingsBusy(true); void api.llmSettings().then(setSettings).catch((caught) => setToast(caught instanceof Error ? caught.message : "模型设置读取失败")).finally(() => setSettingsBusy(false)); };
  const saveSettings = async () => { if (settingsBusy) return; setSettingsBusy(true); try { const updated = await api.saveLlmSettings({ ...(apiKeyDraft.trim() ? { apiKey: apiKeyDraft.trim() } : {}) }); setSettings(updated); setApiKeyDraft(""); setToast(updated.configured ? "DeepSeek API Key 已启用" : "模型设置已保存，但尚未配置 API Key"); } catch (caught) { setToast(caught instanceof Error ? caught.message : "模型设置保存失败"); } finally { setSettingsBusy(false); } };
  const handleFile = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { const content = String(reader.result ?? ""); setScriptText(content.slice(0, MAX_SCRIPT_LENGTH)); if (content.length > MAX_SCRIPT_LENGTH) setToast("文件内容超过 200000 字符，已截取前 200000 字符"); }; reader.readAsText(file, "utf-8"); event.target.value = ""; };
  const navigate = (nextStage: Stage) => { const required: Record<Stage, boolean> = { setup: Boolean(project), format: Boolean(project), episodes: pipeline.document?.formatStatus === "formatted", subjects: pipeline.episodes.length > 0, shots: pipeline.subjects.length > 0, render: pipeline.shots.length > 0 }; if (!required[nextStage]) { setToast(`请先完成「${stages[Math.max(0, stages.findIndex((item) => item.id === nextStage) - 1)].label}」`); return; } setStage(nextStage); setMobileNavOpen(false); };
  const newWorkflow = () => { setProjectManagerVisible(false); setNewProjectDialogOpen(true); };
  const openProjectManager = () => { setProjectManagerVisible(true); void refreshProjectManager(); };
  const chooseNewProjectMode = (hasScript: boolean) => { setNewProjectDialogOpen(false); setProject(null); setHomeVisible(false); window.scrollTo(0, 0); setPipeline(emptyPipeline()); setScriptText(""); setSetupDraft({ title: "", logline: "", genre: "悬疑", style: "电影写实", aspectRatio: "16:9", durationSeconds: 60, targetEpisodeCount: 3 }); setStage(hasScript ? "format" : "setup"); setMobileNavOpen(false); };
  const goHome = () => { setProject(null); setHomeVisible(true); setProjectManagerVisible(false); window.scrollTo(0, 0); setStage("setup"); setMobileNavOpen(false); };

  if (loading) return <div className="loading-screen"><LoaderCircle className="spin" size={24} /><span>正在载入工作区</span></div>;
  if (homeVisible) return <div className="app-shell home-shell"><header className="topbar home-topbar"><a className="brand" href="#home" onClick={(event) => { event.preventDefault(); goHome(); }}><span className="brand-mark"><Film size={18} /></span><span className="brand-name">拥抱世界</span><span className="brand-code">/ SCRIPT TO VIDEO</span></a><div className="home-topbar-title" aria-hidden="true" /> <div className="top-actions"><button className="text-button home-manager-button" onClick={openProjectManager}><FolderOpen size={15} />项目管理</button><span className="connection"><i />LOCAL WORKSPACE</span><button className="icon-button" aria-label="模型设置" onClick={openSettings}><Settings2 size={17} /></button><span className="avatar">M</span></div></header>{error ? <div className="fatal-state home-fatal"><h2>工作区暂时无法连接</h2><p>{error}</p><button className="primary-button" onClick={() => void refresh()}>重新连接</button></div> : projectManagerVisible ? <ProjectManagerStage projects={managerProjects} loading={managerLoading} onBack={goHome} onOpen={(item, target) => void loadProject(item, target)} onDelete={deleteProject} onNew={newWorkflow} /> : <HomeStage projects={dashboard?.projects ?? []} projectCount={dashboard?.stats.projectCount ?? 0} onNew={newWorkflow} onManage={openProjectManager} onOpen={(item, target) => void loadProject(item, target)} onDelete={deleteProject} />}{newProjectDialogOpen && <NewProjectDialog onHasScript={() => chooseNewProjectMode(true)} onNoScript={() => chooseNewProjectMode(false)} onClose={() => setNewProjectDialogOpen(false)} />}{deleteTarget && <DeleteProjectDialog project={deleteTarget} busy={workingAction === "delete"} onConfirm={confirmDeleteProject} onClose={() => setDeleteTarget(null)} />}{settingsOpen && <SettingsDialog settings={settings} draft={apiKeyDraft} busy={settingsBusy} onDraftChange={setApiKeyDraft} onSave={() => void saveSettings()} onClose={() => setSettingsOpen(false)} />}{toast && <div className="toast"><Check size={16} />{toast}</div>}</div>;
  return <div className="app-shell project-shell">
    <header className="topbar project-topbar"><div className="topbar-left"><a className="brand" href="#home" onClick={(event) => { event.preventDefault(); goHome(); }} aria-label="返回拥抱世界首页"><span className="brand-mark"><Film size={18} /></span><span className="brand-name">拥抱世界</span></a></div><nav className="top-steps" aria-label="项目处理步骤">{stages.slice(0, 5).map((item, index) => { const done = index < currentIndex || (item.id === "format" && Boolean(pipeline.document)) || (item.id === "episodes" && pipeline.episodes.length > 0) || (item.id === "subjects" && pipeline.subjects.length > 0) || (item.id === "shots" && pipeline.shots.length > 0); return <button key={item.id} className={`${stage === item.id ? "active" : ""} ${done ? "done" : ""}`} onClick={() => navigate(item.id)}><span>{done ? <Check size={12} /> : index + 1}</span>{item.label}</button>; })}</nav><div className="top-actions"><span className="project-top-title">{project?.title || setupDraft.title || "新建项目"}</span><button className="icon-button" aria-label="模型设置" onClick={openSettings}><Settings2 size={17} /></button><span className="avatar">M</span></div></header>
    <main id="workspace" className="workspace"><div className="workspace-head"><div><h1>{stages[currentIndex].label}</h1><p>{stages[currentIndex].description}，每一步的结果都会成为下一步的输入。</p></div><div className="head-tools"><span className="workspace-progress">项目进度 {completion}%</span><button className="icon-button"><MoreHorizontal size={18} /></button></div></div>{error ? <div className="fatal-state"><h2>工作区暂时无法连接</h2><p>{error}</p><button className="primary-button" onClick={() => void refresh()}>重新连接</button></div> : <div className="work-area"><section className={`canvas-panel ${stage === "setup" ? "setup-canvas-panel" : ""}`}>{stage === "setup" && <SetupStage draft={setupDraft} setDraft={setSetupDraft} onNext={project ? saveProjectSetup : generateProjectScript} working={workingAction === "setup" || workingAction === "generate"} generate={!project} />}{stage === "format" && pipeline.document?.formatStatus === "formatted" ? <FormatStage document={pipeline.document} onNext={extractEpisodes} working={workingAction === "episodes"} /> : stage === "format" ? <ImportStage text={scriptText} setText={setScriptText} onFile={() => fileInput.current?.click()} onNext={formatScript} working={workingAction === "format"} fileInput={fileInput} onFileChange={handleFile} /> : null}{stage === "episodes" && <EpisodesStage episodes={pipeline.episodes} onNext={extractSubjects} working={workingAction === "subjects"} />}{stage === "subjects" && <SubjectsStage subjects={pipeline.subjects} onNext={extractShots} working={workingAction === "shots"} />}{stage === "shots" && <ShotsStage shots={pipeline.shots} episodes={pipeline.episodes} onNext={renderVideo} working={workingAction === "render"} />}{stage === "render" && <RenderStage project={project} shots={pipeline.shots} jobs={dashboard?.jobs ?? []} onBack={() => setStage("shots")} onRender={renderVideo} working={workingAction === "render"} />}</section><Inspector stage={stage} project={project} pipeline={pipeline} /></div>}</main>{settingsOpen && <SettingsDialog settings={settings} draft={apiKeyDraft} busy={settingsBusy} onDraftChange={setApiKeyDraft} onSave={() => void saveSettings()} onClose={() => setSettingsOpen(false)} />}{toast && <div className="toast"><Check size={16} />{toast}</div>}
  </div>;
}

type ProjectDraft = { title: string; logline: string; genre: string; style: string; aspectRatio: string; durationSeconds: number; targetEpisodeCount: number };
type SelectOption = { value: string; label: string };

function HomeStage({ projects, projectCount, onNew, onManage, onOpen, onDelete }: { projects: Project[]; projectCount: number; onNew: () => void; onManage: () => void; onOpen: (project: Project, stage?: Stage) => void; onDelete: (project: Project) => void }) {
  const featured = projects[0];
  return <main id="home" className="home-content"><section className="home-hero"><div className="hero-copy"><span className="panel-eyebrow">SCRIPT TO VIDEO / LOCAL AI WORKSPACE</span><h1>把剧本，变成<br /><em>可见的故事。</em></h1><p>从项目设定开始，经过剧本格式化、分集解析、主体生成和故事板，一条流水线完成视频创作准备。</p><div className="hero-actions"><button className="primary-button" onClick={onNew}>新建项目</button></div></div><div className="hero-showcase">{featured?.coverUrl ? <img src={featured.coverUrl} alt="" /> : <div className="showcase-placeholder"><Film size={42} /><span>YOUR NEXT FILM</span></div>}<div className="showcase-shade" /><div className="showcase-copy"><span>FEATURED PROJECT</span><strong>{featured?.title ?? "YOUR NEXT FILM"}</strong><small>{featured?.style ?? "从一份剧本开始"}</small></div><div className="showcase-index">01 <i /> 05</div></div></section><section className="home-section"><div className="home-section-head"><div><span className="panel-eyebrow">YOUR PROJECTS</span><h2>最近的项目</h2></div><div className="home-section-tools"><span className="project-count">{projectCount} 个项目</span><button className="text-button" onClick={onManage}><FolderOpen size={14} />项目管理</button></div></div>{projects.length ? <div className="home-project-grid">{projects.slice(0, 6).map((item) => <ProjectCard key={item.id} project={item} onOpen={onOpen} onDelete={onDelete} />)}</div> : <div className="home-empty"><Film size={26} /><p>还没有项目，从一份剧本开始。</p><button className="secondary-button" onClick={onNew}><Plus size={16} /> 新建第一个项目</button></div>}{projectCount > 6 && <button className="project-more-guide" onClick={onManage}><span><ListFilter size={16} /><strong>查看更多项目</strong><small>全部 {projectCount} 个项目可在项目管理中搜索和筛选</small></span><ArrowRight size={17} /></button>}</section><section className="home-pipeline"><div><span className="panel-eyebrow">PIPELINE</span><h2>一条清晰的创作路径</h2></div><div className="pipeline-cards">{stages.slice(0, 5).map((item, index) => { const Icon = item.icon; return <div className="pipeline-card" key={item.id}><span>0{index + 1}</span><Icon size={19} /><strong>{item.label}</strong><small>{item.description}</small></div>; })}</div></section></main>;
}

function ProjectCard({ project, onOpen, onDelete }: { project: Project; onOpen: (project: Project, stage?: Stage) => void; onDelete: (project: Project) => void }) {
  const truncateLogline = (text: string) => text.length > 100 ? `${text.slice(0, 100)}...` : text;
  return <article className="home-project-card"><div className="home-project-cover">{project.coverUrl ? <img src={project.coverUrl} alt="" /> : <Film size={28} />}<span>{project.status === "completed" ? "已完成" : `${project.progress}% 进行中`}</span></div><div className="home-project-body"><div className="home-project-heading"><div><span className="project-genre">{project.genre}</span><strong>{project.title}</strong></div><button className="icon-button small-icon delete-project-button" aria-label={`删除项目 ${project.title}`} title="删除项目" onClick={() => onDelete(project)}><Trash2 size={15} /></button></div><p>{truncateLogline(project.logline || "尚未填写项目简介")}</p><div className="home-project-meta"><span>{project.style}</span><span>{project.aspectRatio}</span><span>{project.durationSeconds}s / 集</span></div><div className="home-project-actions"><button className="secondary-button" onClick={() => onOpen(project)}><FolderOpen size={15} /> 进入项目</button><button className="text-button" onClick={() => onOpen(project, "episodes")}><Layers3 size={15} /> 剧本解析</button></div></div></article>;
}

function ProjectManagerStage({ projects, loading, onBack, onOpen, onDelete, onNew }: { projects: Project[]; loading: boolean; onBack: () => void; onOpen: (project: Project, stage?: Stage) => void; onDelete: (project: Project) => void; onNew: () => void }) {
  const [query, setQuery] = useState("");
  const [matchMode, setMatchMode] = useState<"fuzzy" | "exact">("fuzzy");
  const normalizedQuery = query.trim().toLocaleLowerCase();
  const filtered = projects.filter((project) => {
    if (!normalizedQuery) return true;
    const fields = [project.title, project.logline, project.genre, project.style, project.status];
    return matchMode === "exact" ? fields.some((field) => field.toLocaleLowerCase() === normalizedQuery) : fields.some((field) => field.toLocaleLowerCase().includes(normalizedQuery));
  });
  return <main className="manager-content"><div className="manager-head"><div><span className="panel-eyebrow">PROJECT LIBRARY</span><h1>项目管理</h1><p>集中查看所有项目，通过关键词快速定位剧本与创作进度。</p></div><div className="manager-head-actions"><button className="secondary-button" onClick={onBack}><ArrowLeft size={15} /> 返回首页</button><button className="primary-button" onClick={onNew}><Plus size={16} /> 新建项目</button></div></div><div className="manager-toolbar"><label className="manager-search"><Search size={17} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索项目名称、简介、类型或风格" aria-label="搜索项目" /><button className="icon-button small-icon" onClick={() => setQuery("")} disabled={!query} aria-label="清空搜索"><X size={15} /></button></label><div className="manager-filters"><span className="manager-result-count">{loading ? "正在读取" : `找到 ${filtered.length} 个项目`}</span><div className="match-toggle" role="group" aria-label="匹配方式"><button className={matchMode === "fuzzy" ? "selected" : ""} onClick={() => setMatchMode("fuzzy")}><ListFilter size={14} />模糊匹配</button><button className={matchMode === "exact" ? "selected" : ""} onClick={() => setMatchMode("exact")}><Search size={14} />精确匹配</button></div></div></div>{loading ? <div className="manager-empty"><LoaderCircle className="spin" size={22} /><p>正在载入项目库</p></div> : filtered.length ? <div className="manager-grid">{filtered.map((item) => <ProjectCard key={item.id} project={item} onOpen={onOpen} onDelete={onDelete} />)}</div> : <div className="manager-empty"><Search size={24} /><p>{query ? "没有找到匹配的项目" : "还没有项目"}</p><small>{query ? "换一个关键词或切换匹配方式试试" : "从新建项目开始你的创作"}</small></div>}</main>;
}

function NewProjectDialog({ onHasScript, onNoScript, onClose }: { onHasScript: () => void; onNoScript: () => void; onClose: () => void }) {
  return <div className="settings-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="new-project-dialog" role="dialog" aria-modal="true" aria-labelledby="new-project-title"><div className="settings-dialog-head"><div><span className="panel-eyebrow">NEW PROJECT</span><h2 id="new-project-title">先选择你的创作起点</h2><p>已有剧本直接进入格式化，没有剧本则先设定项目并生成剧本。</p></div><button className="icon-button" onClick={onClose} aria-label="关闭新建项目"><X size={18} /></button></div><div className="new-project-options"><button className="new-project-option" onClick={onHasScript}><span className="new-project-option-icon"><FileText size={19} /></span><span><strong>已有剧本</strong><small>粘贴或导入剧本，直接开始格式化</small></span><ArrowRight size={17} /></button><button className="new-project-option" onClick={onNoScript}><span className="new-project-option-icon accent"><WandSparkles size={19} /></span><span><strong>没有剧本</strong><small>填写项目设定，由模型生成剧本草案</small></span><ArrowRight size={17} /></button></div></section></div>;
}

function DeleteProjectDialog({ project, busy, onConfirm, onClose }: { project: Project; busy: boolean; onConfirm: () => void; onClose: () => void }) {
  return <div className="settings-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="settings-dialog delete-project-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-project-title"><div className="settings-dialog-head"><div><span className="panel-eyebrow">DELETE PROJECT</span><h2 id="delete-project-title">确定删除这个项目吗？</h2></div><button className="icon-button" onClick={onClose} aria-label="关闭删除确认" disabled={busy}><X size={18} /></button></div><div className="delete-project-warning"><Trash2 size={18} /><p>项目“<strong>{project.title}</strong>”及其剧本、分集、主体和分镜数据将一并删除，且无法恢复。</p></div><div className="settings-actions"><button className="secondary-button" onClick={onClose} disabled={busy}>取消</button><button className="danger-button" onClick={onConfirm} disabled={busy}>{busy ? <LoaderCircle className="spin" size={15} /> : <Trash2 size={15} />}确认删除</button></div></section></div>;
}

function SmoothSelect({ value, options, onChange, ariaLabel }: { value: string; options: SelectOption[]; onChange: (value: string) => void; ariaLabel: string }) {
  const [open, setOpen] = useState(false);
  const container = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!open) return; const close = (event: MouseEvent) => { if (container.current && !container.current.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, [open]);
  const selected = options.find((option) => option.value === value) ?? options[0];
  return <div className={`smooth-select ${open ? "is-open" : ""}`} ref={container}><button type="button" className="smooth-select-trigger" aria-label={ariaLabel} aria-haspopup="listbox" aria-expanded={open} onClick={() => setOpen((current) => !current)}><span>{selected?.label ?? value}</span><ChevronDown size={16} /></button>{open && <div className="smooth-select-menu" role="listbox" aria-label={ariaLabel}>{options.map((option) => <button type="button" role="option" aria-selected={option.value === value} className={option.value === value ? "selected" : ""} key={option.value} onClick={() => { onChange(option.value); setOpen(false); }}>{option.label}{option.value === value && <Check size={14} />}</button>)}</div>}</div>;
}

function SetupStage({ draft, setDraft, onNext, working, generate }: { draft: ProjectDraft; setDraft: React.Dispatch<React.SetStateAction<ProjectDraft>>; onNext: () => void; working: boolean; generate: boolean }) {
  const change = (key: keyof ProjectDraft, value: string | number) => setDraft((current) => ({ ...current, [key]: value }));
  return <div className="stage-view setup-view"><StepHeader eyebrow="01 / PROJECT SETUP" title="先定义这个故事的边界" description="设定画面比例、类型和整体风格，后续格式化、主体生成与故事板都会以此为统一基准。" /><div className="setup-form"><label className="setup-title"><span>项目名称</span><input value={draft.title} onChange={(event) => change("title", event.target.value)} placeholder="例如：午夜车站" /></label><label className="setup-wide"><span>一句话简介</span><textarea value={draft.logline} maxLength={5000} onChange={(event) => change("logline", event.target.value)} placeholder="描述故事的核心冲突或人物目标" /><small className="field-counter">{draft.logline.length} / 5000</small></label><div className="setup-field setup-genre"><span>内容类型</span><SmoothSelect value={draft.genre} onChange={(value) => change("genre", value)} ariaLabel="内容类型" options={["悬疑", "剧情", "科幻", "都市情感", "奇幻", "短片"].map((value) => ({ value, label: value }))} /></div><div className="setup-field"><span>视觉风格</span><SmoothSelect value={draft.style} onChange={(value) => change("style", value)} ariaLabel="视觉风格" options={["电影写实", "赛博电影", "胶片写实", "日系动画", "国风水墨", "3D 渲染"].map((value) => ({ value, label: value }))} /></div><div className="setup-field"><span>画面比例</span><SmoothSelect value={draft.aspectRatio} onChange={(value) => change("aspectRatio", value)} ariaLabel="画面比例" options={[{ value: "16:9", label: "16:9 · 横屏" }, { value: "9:16", label: "9:16 · 竖屏" }, { value: "1:1", label: "1:1 · 方形" }]} /></div><label className="setup-duration"><span>每集目标时长（秒）</span><input type="number" min="15" max="720" value={draft.durationSeconds} onChange={(event) => change("durationSeconds", Math.min(720, Math.max(15, Number(event.target.value) || 60)))} /></label><label className="setup-episode-count"><span>目标集数</span><input type="number" min="1" max="100" value={draft.targetEpisodeCount} onChange={(event) => change("targetEpisodeCount", Math.min(100, Math.max(1, Number(event.target.value) || 3)))} /></label></div><div className="setup-spacer" /><div className="action-row setup-actions"><span className="action-hint"><Settings2 size={15} /> {generate ? "项目设定将传给模型，生成一份可继续格式化的剧本" : "项目设定完成后进入剧本格式化"}</span><button className="primary-button" onClick={onNext} disabled={working || !draft.title.trim()}>{working ? <LoaderCircle className="spin" size={17} /> : generate ? <WandSparkles size={17} /> : <Check size={17} />}{generate ? "开始生成剧本" : "保存设定，下一步"}{!generate && <ArrowRight size={16} />}</button></div></div>;
}

function StepHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="step-header"><div><span className="panel-eyebrow">{eyebrow}</span><h2>{title}</h2><p>{description}</p></div>{action}</div>; }
function ImportStage({ text, setText, onFile, onNext, working, fileInput, onFileChange }: { text: string; setText: (value: string) => void; onFile: () => void; onNext: () => void; working: boolean; fileInput: React.RefObject<HTMLInputElement | null>; onFileChange: (event: ChangeEvent<HTMLInputElement>) => void }) { return <div className="stage-view import-view"><StepHeader eyebrow="01 / SOURCE SCRIPT" title="把剧本放进来" description="支持纯文本、Markdown 或直接粘贴。先保留原始内容，后续步骤会生成可回溯的结构化版本。" action={<button className="secondary-button" onClick={() => setText(sampleScript)}><Sparkles size={15} /> 使用示例</button>} /><div className="editor-shell"><div className="editor-toolbar"><span className="file-label"><FileText size={15} /> {text ? `${text.split("\n")[0].slice(0, 22)}.txt` : "未命名剧本.txt"}</span><span className="toolbar-muted">UTF-8 · {text.length} / 200000 字</span><button className="toolbar-upload" onClick={onFile}><Upload size={14} /> 导入文件</button><input ref={fileInput} type="file" accept=".txt,.md,.markdown" hidden onChange={onFileChange} /></div><textarea className="script-editor" value={text} maxLength={MAX_SCRIPT_LENGTH} onChange={(event) => setText(event.target.value)} placeholder="在这里粘贴剧本……\n\n建议包含：场次、时间地点、人物、动作和对白。" spellCheck={false} /><div className="editor-foot"><span><i className={text.length >= 30 ? "ready" : ""} />{text.length >= 30 ? "内容已就绪，可以开始格式化" : "至少输入 30 个字符"}</span><span>{text.length} / 200000 字 · {text.split(/\s+/).filter(Boolean).length} tokens</span></div></div><div className="action-row"><span className="action-hint"><WandSparkles size={15} /> 下一步会识别场次、人物和对白结构</span><button className="primary-button" onClick={onNext} disabled={working || text.trim().length < 30}>{working ? <LoaderCircle className="spin" size={17} /> : <WandSparkles size={17} />}格式化剧本 <ArrowRight size={16} /></button></div></div>; }
function FormatStage({ document, onNext, working }: { document: PipelineData["document"]; onNext: () => void; working: boolean }) { return <div className="stage-view"><StepHeader eyebrow="02 / FORMAT" title="标准化剧本格式" description="统一场次、人物、动作和对白标记，后续提取会以这份结构化文本为准。" action={<span className="ready-badge"><Check size={14} /> 原文保真</span>} /><div className="compare-grid"><div className="text-pane"><div className="pane-head"><span>原始文本</span><small>READ ONLY</small></div><pre>{document?.originalText}</pre></div><div className="text-pane formatted"><div className="pane-head"><span>标准格式</span><small>READ ONLY</small></div><pre>{document?.formattedText}</pre></div></div><div className="action-row"><span className="action-hint"><Check size={15} /> 原文已单独归档，可进入分集</span><button className="primary-button" onClick={onNext} disabled={working}>{working ? <LoaderCircle className="spin" size={17} /> : <Layers3 size={17} />}提取分集 <ArrowRight size={16} /></button></div></div>; }
function EpisodesStage({ episodes, onNext, working }: { episodes: Episode[]; onNext: () => void; working: boolean }) { return <div className="stage-view"><StepHeader eyebrow="03 / EPISODES" title="分集结构" description="将长篇故事拆成可独立生产的集数。每集都可以单独提取主体和分镜。" action={<button className="secondary-button"><Plus size={15} /> 添加一集</button>} /><div className="episode-list">{episodes.map((episode) => <EpisodeCard key={episode.id} episode={episode} />)}</div><div className="action-row"><span className="action-hint"><Layers3 size={15} /> {episodes.length} 集 · 结构已建立</span><button className="primary-button" onClick={onNext} disabled={working || !episodes.length}>{working ? <LoaderCircle className="spin" size={17} /> : <UsersRound size={17} />}提取主体 <ArrowRight size={16} /></button></div></div>; }

function DetailField({ label, value }: { label: string; value: string }) { return <div className="detail-field"><span>{label}</span><p>{value || "未设定"}</p></div>; }

function EpisodeCard({ episode }: { episode: Episode }) {
  const [open, setOpen] = useState(false);
  const plotNodes = episode.plotNodes ?? [];
  const characters = episode.characters ?? [];
  return <article className={`episode-card ${open ? "is-open" : ""}`}>
    <span className="episode-index">E{String(episode.episodeNumber).padStart(2, "0")}</span>
    <div className="episode-main">
      <div className="edit-line"><input defaultValue={episode.title} aria-label={`第${episode.episodeNumber}集标题`} /><span className="status-chip"><Check size={12} /> AI STRUCTURED</span></div>
      <p className="episode-summary">{episode.summary}</p>
      <div className="episode-meta"><span><Film size={13} /> {episode.sceneCount || "—"} 场</span><span><Clapperboard size={13} /> 可提取分镜</span><span>{characters.length} 位人物</span></div>
      <button className="episode-view-button" onClick={() => setOpen((current) => !current)} aria-expanded={open}><FileText size={15} /> {open ? "收起本集内容" : "查看本集完整内容"}<ChevronDown size={15} className={open ? "rotate" : ""} /></button>
      {open && <div className="episode-detail">
        <div className="episode-detail-grid">
          <section className="episode-detail-section hook-section"><div className="detail-section-title"><Sparkles size={15} /><h3>本集钩子</h3></div><p>{episode.hook || "未明确设定"}</p></section>
          <section className="episode-detail-section"><div className="detail-section-title"><Layers3 size={15} /><h3>情节节点</h3></div>{plotNodes.length ? <ol className="plot-node-list">{plotNodes.map((node, index) => <li key={`${episode.id}-plot-${index}`}><b>{String(index + 1).padStart(2, "0")}</b><span>{node}</span></li>)}</ol> : <p className="empty-detail">未返回情节节点</p>}</section>
        </div>
        <section className="episode-detail-section original-section"><div className="detail-section-title"><FileText size={15} /><h3>本集格式化内容</h3><span>来自标准格式</span></div><pre>{episode.originalText || "未返回本集格式化内容"}</pre></section>
        <section className="episode-detail-section characters-section"><div className="detail-section-title"><UsersRound size={15} /><h3>参与人物</h3><span>{characters.length} 人</span></div>{characters.length ? <div className="character-grid">{characters.map((character, index) => <article className="character-profile" key={`${episode.id}-character-${character.name}-${index}`}><div className="character-profile-head"><div className="character-avatar"><UsersRound size={16} /></div><strong>{character.name}</strong></div><div className="character-fields"><DetailField label="人物介绍" value={character.introduction} /><DetailField label="穿着" value={character.costume} /><DetailField label="性格" value={character.personality} /><DetailField label="表情 / 状态" value={character.expressions} /><DetailField label="连续性备注" value={character.continuityNotes} /></div></article>)}</div> : <p className="empty-detail">本集未识别到参与人物</p>}</section>
      </div>}
    </div>
    <button className="icon-button small-icon" aria-label="分集更多"><MoreHorizontal size={16} /></button>
  </article>;
}
const roleLabels: Record<Subject["role"], string> = { character: "角色", location: "场景", prop: "道具" };
function SubjectCard({ subject }: { subject: Subject }) {
  return <article className="subject-card">
    <div className={`subject-avatar ${subject.role}`}><UsersRound size={19} /></div>
    <div className="subject-card-main">
      <div><strong>{subject.name}</strong><span className={`role-label ${subject.role}`}>{roleLabels[subject.role]}</span></div>
      <div className="subject-card-details">
        <div><span>主体描述</span><p>{subject.description || "未设定"}</p></div>
        <div><span>视觉提示词</span><p>{subject.visualPrompt || "未设定"}</p></div>
      </div>
    </div>
  </article>;
}
function SubjectsStage({ subjects, onNext, working }: { subjects: Subject[]; onNext: () => void; working: boolean }) { return <div className="stage-view"><StepHeader eyebrow="04 / SUBJECTS" title="主体资产" description="先固定故事里会反复出现的角色、场景与关键道具，保证后续画面的一致性。" action={<button className="secondary-button"><Plus size={15} /> 添加主体</button>} /><div className="subject-grid">{subjects.map((subject) => <SubjectCard key={subject.id} subject={subject} />)}</div><div className="action-row"><span className="action-hint"><UsersRound size={15} /> {subjects.length} 个主体 · 已生成视觉提示词</span><button className="primary-button" onClick={onNext} disabled={working || !subjects.length}>{working ? <LoaderCircle className="spin" size={17} /> : <ScanSearch size={17} />}提取分镜 <ArrowRight size={16} /></button></div></div>; }
function ShotsStage({ shots, episodes, onNext, working }: { shots: Shot[]; episodes: Episode[]; onNext: () => void; working: boolean }) { const [selectedEpisode, setSelectedEpisode] = useState(0); const visible = selectedEpisode ? shots.filter((shot) => shot.episodeNumber === selectedEpisode) : shots; return <div className="stage-view shots-view"><StepHeader eyebrow="05 / STORYBOARD" title="分镜清单" description="按集查看镜头、场景调度和对白。确认后即可把镜头送入视频生成。" action={<div className="episode-tabs"><button className={selectedEpisode === 0 ? "selected" : ""} onClick={() => setSelectedEpisode(0)}>全部</button>{episodes.map((episode) => <button key={episode.id} className={selectedEpisode === episode.episodeNumber ? "selected" : ""} onClick={() => setSelectedEpisode(episode.episodeNumber)}>E{String(episode.episodeNumber).padStart(2, "0")}</button>)}</div>} /><div className="shot-table"><div className="shot-table-head"><span>镜头</span><span>场景 / 动作</span><span>对白</span><span>画面提示词</span><span>时长</span></div>{visible.map((shot) => <article className="shot-row" key={shot.id}><span className="shot-number">E{String(shot.episodeNumber).padStart(2, "0")} · {String(shot.shotOrder).padStart(2, "0")}<strong>{shot.title.split("·").slice(1).join("·").trim()}</strong></span><span><b>{shot.location}</b><small>{shot.action}</small></span><span className="dialogue">{shot.dialogue || "—"}</span><span className="shot-prompt">{shot.visualPrompt}</span><span className="shot-duration">{shot.durationSeconds}s<i>{shot.camera}</i></span></article>)}</div><div className="action-row"><span className="action-hint"><ScanSearch size={15} /> {shots.length} 个镜头 · 预估 {formatDuration(shots.reduce((sum, shot) => sum + shot.durationSeconds, 0))}</span><button className="primary-button" onClick={onNext} disabled={working || !shots.length}>{working ? <LoaderCircle className="spin" size={17} /> : <Clapperboard size={17} />}生成视频 <ArrowRight size={16} /></button></div></div>; }
function RenderStage({ project, shots, jobs, onBack, onRender, working }: { project: Project | null; shots: Shot[]; jobs: DashboardData["jobs"]; onBack: () => void; onRender: () => void; working: boolean }) {
  const active = jobs.find((job) => job.projectId === project?.id);
  const [ratio, setRatio] = useState(project?.aspectRatio ?? "16:9");
  const [style, setStyle] = useState(project?.style ?? "电影写实");
  const [audio, setAudio] = useState("保留对白");
  return <div className="stage-view render-view"><StepHeader eyebrow="06 / VIDEO OUTPUT" title="生成视频" description="镜头已准备好。选择输出规格，提交后会进入本地渲染队列。" action={<span className="engine-tag"><i /> VIDEO ENGINE · LOCAL MOCK</span>} /><div className="render-preview"><div className="preview-art"><div className="preview-grid" /><span className="preview-play"><Play size={20} fill="currentColor" /></span><div className="preview-caption"><span>READY TO RENDER</span><strong>{project?.title}</strong></div></div><div className="render-settings"><div className="settings-heading"><Settings2 size={16} /> 输出设置</div><label>画面比例<SmoothSelect value={ratio} onChange={setRatio} ariaLabel="输出画面比例" options={[{ value: "16:9", label: "16:9 · 横屏" }, { value: "9:16", label: "9:16 · 竖屏" }, { value: "1:1", label: "1:1 · 方形" }]} /></label><label>视频风格<SmoothSelect value={style} onChange={setStyle} ariaLabel="输出视频风格" options={["电影写实", "赛博电影", "日系动画", "国风水墨"].map((value) => ({ value, label: value }))} /></label><label>音频策略<SmoothSelect value={audio} onChange={setAudio} ariaLabel="音频策略" options={["保留对白", "自动配音", "暂不生成音频"].map((value) => ({ value, label: value }))} /></label><div className="render-summary"><span>镜头数量 <b>{shots.length}</b></span><span>预计时长 <b>{formatDuration(shots.reduce((sum, shot) => sum + shot.durationSeconds, 0))}</b></span></div></div></div>{active && <div className="active-job"><span className="job-spinner"><LoaderCircle className="spin" size={17} /></span><div><strong>正在处理：{active.projectTitle}</strong><p>视频合成中，当前进度 {active.progress}%</p></div><b>{active.progress}%</b><i><span style={{ width: `${active.progress}%` }} /></i></div>}<div className="action-row"><button className="secondary-button" onClick={onBack}><ArrowLeft size={16} /> 返回分镜</button><button className="primary-button" onClick={onRender} disabled={working || Boolean(active?.status === "processing")}>{working ? <LoaderCircle className="spin" size={17} /> : <Clapperboard size={17} />}提交渲染任务 <ArrowRight size={16} /></button></div></div>;
}
function Inspector({ stage, project, pipeline }: { stage: Stage; project: Project | null; pipeline: PipelineData }) { const labels: Record<Stage, string> = { setup: "项目设定", format: "格式化结果", episodes: "剧本解析", subjects: "主体结果", shots: "故事板结果", render: "输出结果" }; return <aside className="inspector"><div className="inspector-head"><span>当前产物</span><button className="icon-button"><MoreHorizontal size={17} /></button></div><div className="inspector-title"><span className="inspector-icon"><Sparkles size={16} /></span><div><strong>{labels[stage]}</strong><small>{project?.title ?? "尚未创建项目"}</small></div></div><div className="inspector-stats"><div><span>进度</span><b>{project?.progress ?? 0}%</b></div><div><span>分集</span><b>{pipeline.episodes.length || "—"}</b></div><div><span>镜头</span><b>{pipeline.shots.length || "—"}</b></div></div><div className="inspector-section"><span className="section-label">流水线状态</span>{stages.slice(1).map((item) => { const ready = item.id === "format" ? Boolean(pipeline.document) : item.id === "episodes" ? pipeline.episodes.length > 0 : item.id === "subjects" ? pipeline.subjects.length > 0 : item.id === "shots" || item.id === "render" ? pipeline.shots.length > 0 : false; return <div className="status-line" key={item.id}><span className={ready ? "status-check ready" : "status-check"}>{ready && <Check size={11} />}</span><span>{item.label}</span><small>{ready ? "已完成" : "待处理"}</small></div>; })}</div><div className="inspector-tip"><Sparkles size={15} /><p>分集、主体和分镜会调用 DeepSeek v4 Flash；未配置 Key 时会阻止模型步骤，不生成示例结果。</p></div></aside>; }

function SettingsDialog({ settings, draft, busy, onDraftChange, onSave, onClose }: { settings: LlmSettings | null; draft: string; busy: boolean; onDraftChange: (value: string) => void; onSave: () => void; onClose: () => void }) { return <div className="settings-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="settings-dialog" role="dialog" aria-modal="true" aria-labelledby="settings-title"><div className="settings-dialog-head"><div><span className="panel-eyebrow">MODEL SETTINGS</span><h2 id="settings-title">DeepSeek 模型配置</h2></div><button className="icon-button" onClick={onClose} aria-label="关闭模型设置"><X size={18} /></button></div>{busy && !settings ? <div className="settings-loading"><LoaderCircle className="spin" size={19} />正在读取本地配置</div> : <><div className={`config-status ${settings?.configured ? "configured" : "not-configured"}`}><span className="status-dot" /><div><strong>{settings?.configured ? "API Key 已配置" : "尚未配置 API Key"}</strong><small>{settings?.configured ? "分集、主体、分镜将调用真实模型" : "未配置时不会生成示例结果"}</small></div></div><label className="settings-field">API Key<input type="password" value={draft} onChange={(event) => onDraftChange(event.target.value)} placeholder={settings?.configured ? "已配置，输入新 Key 可替换" : "粘贴 DeepSeek API Key"} autoComplete="off" /></label><label className="settings-field">模型<input value={settings?.model ?? "deepseek-v4-flash"} readOnly /></label><label className="settings-field">API 地址<input value={settings?.apiBase ?? "https://api.deepseek.com"} readOnly /></label><p className="settings-note">Key 只保存到本机后端的 <code>backend/.env</code>，不会写入剧本数据库或返回到页面。</p><div className="settings-actions"><button className="secondary-button" onClick={onClose}>取消</button><button className="primary-button" onClick={onSave} disabled={busy}>{busy ? <LoaderCircle className="spin" size={16} /> : <Check size={16} />}保存并启用</button></div></>}</section></div>; }
export default App;
